[package]
name = "ya_synth3"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
tonic = { version = "0.12", features = ["tls"] }
prost = "0.13"
tokio = { version = "1", features = ["full"] }


[build-dependencies]
tonic-build = "0.12"
